spring:
  main:
    banner-mode: "off"
    web-application-type: reactive

mail:
  smtpHost: ${SMTP_HOST}
  smtpPort: ${SMTP_PORT}
  smtpUser: ${SMTP_USER}
  smtpPass: ${SMTP_PASS}
  noReplyAddress: ${SMTP_NO_REPLY}

rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  mail:
    queue: ${RABBITMQ_MAILQUEUE}
    exchange: ${RABBITMQ_EXCHANGE}
    routingkey: ${RABBITMQ_ROUTINGKEY}
  invoice:
    invoiceCreatedQueue: ${RABBITMQ_INVOICE_CREATED_QUEUE}
    invoiceCreatedExchange: ${RABBITMQ_INVOICE_CREATED_EXCHANGE}
    invoiceCreatedRoutingkey: ${RABBITMQ_INVOICE_CREATED_ROUTINGKEY}
  promotion:
    categoryPromotionQueue: ${RABBITMQ_CATEGORY_PROMOTION_QUEUE}
    categoryPromotionExchange: ${RABBITMQ_CATEGORY_PROMOTION_EXCHANGE}
    categoryPromotionRoutingkey: ${RABBITMQ_CATEGORY_PROMOTION_ROUTINGKEY}