spring:
  main:
    banner-mode: "off"
    web-application-type: reactive

mail:
  smtpHost: ${SMTP_HOST:smtp.gmail.com}
  smtpPort: ${SMTP_PORT:587}
  smtpUser: ${SMTP_USER:bme.aut.wws.dev@gmail.com}
  smtpPass: ${SMTP_PASS:wwsDEV_bmeaut69*}
  noReplyAddress: ${SMTP_FROM:bme.aut.wws.dev@gmail.com}

rabbitmq:
  host: ${RABBITMQ_HOST:wws_rabbitmq}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:guest}
  password: ${RABBITMQ_PASSWORD:guest}
  mail:
    queue: ${RABBITMQ_MAILQUEUE:mail}
    exchange: ${RABBITMQ_MAILQUEUE:mailQueue}
    routingkey: ${RABBITMQ_MAILQUEUE:mail_queue}
  invoice:
    invoiceCreatedQueue: ${RABBITMQ_INVOICE_CREATED_QUEUE:invoiceCreated}
    invoiceCreatedExchange: ${RABBITMQ__INVOICE_CREATED_EXCHANGEE:invoiceCreatedQueue}
    invoiceCreatedRoutingkey: ${RABBITMQ__INVOICE_CREATED_ROUTINGKEY:invoice_created_queue}
  promotion:
    categoryPromotionQueue: ${RABBITMQ_CATEGORY_PROMOTION_QUEUE:categoryPromotion}
    categoryPromotionExchange: ${RABBITMQ_CATEGORY_PROMOTION_EXCHANGE:categoryPromotionQueue}
    categoryPromotionRoutingkey: ${RABBITMQ_CATEGORY_PROMOTION_ROUTINGKEY:category_promotion_queue}