version: '3.4'

services:
  inventory:
    ports:
    - "8081:8080"
  mail:
    ports:
    - "8084:8080"
  mssql:
    ports:
    - "1433:1433"
  mongodb:
    ports:
      - "27018:27017"
  order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:80"
  user:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8083:80"
  web:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3001:3000"
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
  invoice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8085:80"