spring:
  data:
    mssql:
      host: ${MSSQL_HOST:wws_mssql}
      port: ${MSSQL_PORT:1433}
      database: ${MSSQL_DATABASE:WWS}
      username: ${MSSQL_USERNAME:sa}
      password: ${MSSQL_PASSWORD:WWSPass420*}
    r2dbc:
      repositories:
        enabled: true
  main:
    web-application-type: reactive

logging:
  level:
    hu.bme.aut.inventory: TRACE
    org:
      springframework:
       r2dbc: TRACE

rabbitmq:
  host: ${RABBITMQ_HOST:wws_rabbitmq}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:guest}
  password: ${RABBITMQ_PASSWORD:guest}
  order:
    orderCreatedQueue: ${RABBITMQ_ORDER_CREATED_QUEUE:orderCreated}
    orderCreatedExchange: ${RABBITMQ__ORDER_CREATED_EXCHANGEE:orderCreatedQueue}
    orderCreatedRoutingkey: ${RABBITMQ_ORDER_CREATED_ROUTINGKEY:order_created_queue}