spring:
  data:
    mssql:
      host: ${MSSQL_HOST}
      port: ${MSSQL_PORT}
      database: ${MSSQL_DATABASE}
      username: ${MSSQL_USERNAME}
      password: ${MSSQL_PASSWORD}
    r2dbc:
      repositories:
        enabled: true
  main:
    web-application-type: reactive

logging:
  level:
    hu.bme.aut.inventory: TRACE
    org:
      springframework:
       r2dbc: TRACE

rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  order:
    orderCreatedQueue: ${RABBITMQ_ORDER_CREATED_QUEUE}
    orderCreatedExchange: ${RABBITMQ_ORDER_CREATED_EXCHANGE}
    orderCreatedRoutingkey: ${RABBITMQ_ORDER_CREATED_ROUTINGKEY}
  discount:
    categoryDiscountQueue: ${RABBITMQ_CATEGORY_DISCOUNT_QUEUE}
    categoryDiscountExchange: ${RABBITMQ_CATEGORY_DISCOUNT_EXCHANGE}
    categoryDiscountRoutingkey: ${RABBITMQ_CATEGORY_DISCOUNT_ROUTINGKEY}