FROM node:17-alpine3.14

WORKDIR /code
COPY Web/frontend/package*.json ./
COPY Web/frontend/tsconfig.json ./

RUN npm install

COPY Web/frontend .
COPY Web/frontend/tsconfig.json ./tsconfig.json


EXPOSE 3000

CMD [ "npm", "run", "dev" ]