name: inventory-ci

on:
  push:
    branches: [ main ]
    paths:
      - "src/WWS/Mail/**"
      - ".github/workflows/inventory-ci.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Publish dev image to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: sydnikat/wws-inventory
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./Inventory/inventory/Dockerfile
        context: ./Inventory/inventory
        workdir: src/WWS
        tags: "dev-latest"
