name: mssql-ci

on:
  push:
    branches: [ main ]
    paths:
      - "src/WWS/Mssql/**"
      - ".github/workflows/mssql-ci.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          sydnikat/wws-mssql
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    
    - name: Build and Publish dev image to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: sydnikat/wws-mssql
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Mssql/Docker/Dockerfile
        context: .
        workdir: src/WWS
        tags: "dev-latest,${{ steps.meta.outputs.tags }}"
