name: mssql-ci

on:
  push:
    branches: [ main ]
    paths:
      - "src/WWS/Mssql/**"
      - ".github/workflows/mssql-ci.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build and Publish dev image to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: sydnikat/wws-mssql
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Mssql/Docker/Dockerfile
        context: .
        workdir: src/WWS
        tag_semver: refs/tags/v1.2.3
        # tags: ${{ steps.meta.outputs.tags }}
        # tags: "dev-latest,${{ steps.meta.outputs.tags }}"
